// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CloseTabsToLeftAndRight
{
    static class Vsix
    {
        public const string Id = "17d4b5e5-01a7-4e42-b7a5-ab1fb9e77dda";
        public const string Name = "Close Tabs To Right";
        public const string Description = @"Close document tabs to the right of the current document.";
        public const string Language = "en-US";
        public const string Version = "1.5";
        public const string Author = "Evan Kinney";
        public const string Tags = "close, tab, tabs, to, right, document";
    }
}
